languageCode = "en"
languageName = "English"
weight = 1
title = "METANDATA"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/metandata_isotype_light.png"
  secondaryLogo = "images/metandata_isotype_dark.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

