[[main]]
    # Top-level menu entry
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 1
